### ISSUE TITLE
Support for external templates and stylesheets

### ISSUE THREAD

**Issue by stanvanheumen** [robisim74/angular-library-starter#28]
I have just tried to use the library-starter to compile a component I recently created. This component contains an external template/stylesheet, as such:

```
@Component({
    selector: 'app-card',
    styleUrls: ['./card.component.scss'],
    templateUrl: './card.component.html'
})
export class CardComponent { }
```

Is there in any way support for this kind of configuration?

**Comment by robisim74** [comment]
No, this starter doesn't support external templates and stylesheets: #1

**Comment by fabgallo** [comment]
@stanvanheumen there is a way to do it, by adding a couple of tools (gulp, node-sass, and various plugins) and modifying the the build script. The script will automatically inline both HTML templates and (S)CSS files in the component before starting the compilation. We use it in our own modified version of this awesome library (thanks @robisim74 !). If he is interested in adding this feature, I may try to create a pull request.

**Comment by robisim74** [comment]
@fabgallo really thanks! but the goal of this project is to recreate the building process of the official Angular packages in the simplest possible way and so that everyone can customize it according to their needs. You could create a new project, and I could direct it those who are interested in these features (let me know).
However, in the last few months a lot of projects was born to create Angular libraries: I think that everyone can choose the project that suits him.

**Comment by fabgallo** [comment]
@robisim74 that's exactly the reason why we didn't offer a pull request before. It was clear from [#1](https://github.com/robisim74/angular-library-starter/issues/1) that this library didn't natively support external CSS/templates (we were fine with it when we started using it, then we found out we actually needed it for a couple of components, so we added it ourselves).

Thanks again for your awesome work!
